### ISSUE TITLE
Could not pass ChangeBlockEvent$Modify$Impl to Plugin

### ISSUE THREAD

**Issue by InsaneJ** [rojo8399/Prism#2]
Using Prism-3.0.0-beta2-48-g39b8d2f, spongeforge-1.10.2-2477-5.2.0-BETA-2793 and forge-1.10.2-12.18.3.2511-universal
The following error is spammed in the server log file:
```
[Server thread/ERROR] [Sponge/]: Could not pass ChangeBlockEvent$Modify$Impl to Plugin{id=prism, name=Prism, version=3.0.0, description=A rollback/restore grief-prevention plugin., url=http://helion3.com/, authors=[viveleroi], source=/home/minecraft_ftb02/mods/_Prism-3.0.0-beta2-48-g39b8d2f.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.data.DataContainer.createNew()Lorg/spongepowered/api/data/DataContainer;
        at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.<init>(PrismRecord.java:136) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-48-g39b8d2f+unknown-b0.git-unknown]
        at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.<init>(PrismRecord.java:133) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-48-g39b8d2f+unknown-b0.git-unknown]
        at com.helion3.prism.api.records.PrismRecord$PrismRecordBuilder.source(PrismRecord.java:446) ~[PrismRecord$PrismRecordBuilder.class:3.0.0-beta2-48-g39b8d2f+unknown-b0.git-unknown]
        at com.helion3.prism.listeners.ChangeBlockListener.onChangeBlock(ChangeBlockListener.java:60) ~[ChangeBlockListener.class:3.0.0-beta2-48-g39b8d2f+unknown-b0.git-unknown]
        at org.spongepowered.common.event.listener.ChangeBlockEventListener_ChangeBlockListener_onChangeBlock107.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:629) ~[TrackingUtil.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:536) ~[TrackingUtil.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:85) ~[BlockTickPhaseState.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:85) [BlockTickPhaseState.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:226) [CauseTracker.class:1.10.2-2477-5.2.0-BETA-2793]
        at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:302) [TrackingUtil.class:1.10.2-2477-5.2.0-BETA-2793]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2137) [ls.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
```

I have set Prism to use MySQL. Only two tables were created: prism_extra and prism_records

**Comment by ronaldburns** [comment]
You're on Sponge 5.
This method is only supported in 6+.
Try this sponge version: https://www.spongepowered.org/downloads/spongeforge/bleeding/1.10.2

**Comment by InsaneJ** [comment]
It seems Sponge 6 is running way behind on Sponge 5 for Minecraft 1.10.2 when it comes to Forge support. Sponge 6 seems to support 2123 vs 2477 for Sponge 5 and because of that a lot of mods won't load. We're running the FTB Direwolf 20 pack.

Is it possible to support Sponge 5.2?

**Comment by ronaldburns** [comment]
Ok I understand.
Sadly, the error you're getting is because API 5 doesn't have a class. The class is used in the core parts of the plugin, so it's not easy to change. Looks like Prism is API 6+ for now. Sorry. 😞
